[package]
name = "tron-wallet-miner"
version = "0.1.0"
edition = "2021"

[dependencies]
bip39 = "2.0.0"
bs58 = "0.5.1"
hmac = "0.12.1"
pbkdf2 = "0.12.2"
secp256k1 = "0.29.1"
sha2 = "0.10.8"
sha3 = "0.10.8"
